# Generated by Django 2.1.7 on 2019-05-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='title',
        ),
    ]
