# Generated by Django 2.1.7 on 2019-06-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0004_auto_20190603_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
